[package]
name = "drones"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Utilities
futures = "0.3.28"

ctrlc = "3.4.1"

tokio = { version = "1.33.0", features = ["full"] }
tokio-util = "0.7.10"

geo = "0.26.0"
geo-types = "0.7.11"

