openapi: 3.0.0
info:
  title: Orchestrator Diagnostic API 
  description: Orchestrator HTTP API for diagnostic tools.
  version: 0.0.1
paths:
  /:
    get:
      summary: Obtains Server Status
      responses:
        '200':
          description: Server Status
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ServerStatus"
  /sessions:
    get:
      summary: List with session details
      responses:
        '200':
          description: Session List
  /environment:
    get:
      summary: Playing Environment Data
      responses:
        '200':
          description: Environment Data
components:
  schemas:
    ServerStatus:
      type: object
      properties:
        uptime:
          type: number 
        version:
          type: string
          example: "0.1.5"


