openapi: 3.0.0
info:
  title: Orchestrator Diagnostic API
  description: Orchestrator HTTP API for diagnostic tools.
  version: 0.0.1
paths:
  /:
    get:
      summary: Obtains Server Status
      responses:
        '200':
          description: Server Status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerInformation"
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '429':
          description: Too Many Requests
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /sessions:
    get:
      summary: List with session details
      responses:
        '200':
          description: Successful fetch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionCollection"
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '429':
          description: Too Many Requests
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /environment:
    get:
      summary: Fetch environment details
      responses:
        '200':
          description: Successful fetch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environment"
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        '429':
          description: Too Many Requests
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"

components:
  schemas:
    CoordinatesDto:
      type: object
      properties:
        lng:
          type: number
          format: double
        lat:
          type: number
          format: double

    MissionDto:
      type: object
      properties:
        mission_id:
          type: integer
          format: int64
        active:
          type: boolean
        target:
          $ref: "#/components/schemas/CoordinatesDto"
        waypoints:
          type: array
          items:
            $ref: "#/components/schemas/CoordinatesDto"

    ServerInformation:
      type: object
      properties:
        state:
          type: string
          enum:
            - RUNNING
            - STOPPING
        uptime:
          type: number
          format: float
        tickrate:
          type: number
          format: float
        version:
          type: string
          example: "0.1.5"

    SessionDetailsDTO:
      type: object
      properties:
        system_id:
          type: integer
          format: int32
        agent_id:
          type: integer
          format: int32
        session_id:
          type: integer
          format: int32
        session_status:
          type: string
          enum:
            - IDLE
        coordinates:
          $ref: "#/components/schemas/CoordinatesDto"
        connection_status:
          type: string
          enum:
            - CONNECTED
            - DISCONNECTED
        mission:
          type: object
          nullable: true
          $ref: "#/components/schemas/MissionDto"

    SessionCollection:
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: "#/components/schemas/SessionDetailsDTO"

    BoundsDto:
      type: object
      properties:
        north_west_corner:
          $ref: "#/components/schemas/CoordinatesDto"
        size_degrees:
          type: number
          format: float

    Environment:
      type: object
      properties:
        perimeter:
          type: array
          items:
            $ref: "#/components/schemas/CoordinatesDto"
        cells:
          type: array
          items:
            $ref: "#/components/schemas/BoundsDto"

    Problem:
      type: object
      properties:
        title:
          type: string
        status:
          type: integer
          format: int32
