name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  #build:
  #needs: [formatting]
  # runs-on: ubuntu-latest
  # steps:
  # - uses: actions/checkout@v2
  # - uses: actions-rs/toolchain@v1
  #   with:
  #     profile: minimal
  #     toolchain: stable
  # - name: Build
  #   uses: actions-rs/cargo@v1
  #   with:
  #     command: build
  #     args: --verbose --release
  # - name: List OUT_DIR contents
  #      run: ls -R $OUT_DIR
